services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - rabbitmq_net

    delivery-queue-service:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - rabbitmq
        environment:
            - RABBITMQ_URL=amqp://rabbitmq
            - QUEUE_NAME=delivery_appointments
        networks:
            - rabbitmq_net

networks:
    rabbitmq_net:
        external: true
